permitsPerSecond: 1

server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/db
        username: user
        password: pass

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
                default_schema: public
                show_sql: true
                format_sql: true